version: '3'

services:
  mongo-account:
    image: mongo
    restart: always
    ports:
    - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: account
      MONGO_INITDB_ROOT_PASSWORD: account
    networks:
      - account
  mongo-account-history:
    image: mongo
    restart: always
    ports:
    - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: account-history
      MONGO_INITDB_ROOT_PASSWORD: account-history
    networks:
    - account-history
  mongo-statistics:
    image: mongo
    restart: always
    ports:
    - "27019:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: statistics
      MONGO_INITDB_ROOT_PASSWORD: statistics-history
    networks:
    - statistics
  account-service:
    build: ./account-service
    restart: always
    ports:
    - "8080:8080"
    depends_on:
      - mongo-account
    networks:
      - account
      - moneytracker
  account-history-service:
    build: ./account-history-service
    restart: always
    ports:
    - "8090:8090"
    depends_on:
      - mongo-account-history
    networks:
      - moneytracker
      - account-history
  statistics-service:
    build: ./statistics-service
    restart: always
    ports:
    - "8070:8070"
    networks:
    - statistics
    - moneytracker

networks:
  account:
  account-history:
  statistics:
  moneytracker: