POST {{host}}/api/accounts/{accountId}/balance/subtract HTTP/1.1
Content-Type: application/json

{
  "amount": "20.00",
  "expenseType": "food"
}

###

POST {{host}}/api/accounts/{accountId}/balance/add HTTP/1.1
Content-Type: application/json

{
  "amount": "20.00"
}

###
